global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Frontend application metrics
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # API backend metrics
  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database metrics
  - job_name: 'database'
    static_configs:
      - targets: ['database:1433']
    scrape_interval: 60s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'application-metrics'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    honor_labels: true

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'frontend:3000'
        - 'api:5000'
        - 'database:1433'
        - 'redis:6379'
    metrics_path: '/health'
    scrape_interval: 60s
